#!/bin/sh

. /lib/functions/system.sh
. /lib/functions/uci-defaults.sh
. /lib/functions/touchstar.sh

board=$(boardname_get)

if [ "$board" == "emu" ]; then
	board_config_update	
	
	ucidef_set_interface_lan "eth0"
	ucidef_set_interface_raw "ts" "eth1" "dhcp"

	board_config_flush
fi
