#!/bin/sh

. /lib/ar71xx.sh

board=$(ar71xx_board_name)

case "$board" in
ts-vh401)
		# rather than disabling rebind protection, let's just allow it for "our" domains.
	uci add_list dhcp.@dnsmasq[0].rebind_domain='touchstar.com.au'
	uci add_list dhcp.@dnsmasq[0].rebind_domain='touchstar.biz'
 	uci commit dhcp

		# enabled wifi and set default SSID (restart once uci is set)
	uci set wireless.@wifi-iface[0].ssid='IntelLINK'
  uci set wireless.@wifi-device[0].disabled=0
  uci commit wireless
  wifi

		# setup 3g cellular and set APN.
  uci set network.wan=interface
  uci set network.wan.proto='3g'
  uci set network.wan.device='/dev/ttyUSB3'
  uci set network.wan.service='umts'
 	uci set network.wan.apn='telstra.internet'

	uci set autossh.@autossh[0].ssh='-i /etc/dropbear/id_rsa -N -T -R *:30001:localhost:22 device@machine20.touchstar.com.au'
	uci set autossh.@autossh[0].monitorport='0'
  uci set autossh.@autossh[0].poll='300'
	uci commit autossh

		# disable ipv6 for test network given issues on TS network with device becoming primary dns resolved for link-local.
  uci delete network.ts6
  uci commit network
	;;
esac
